version: '3.6'

services:
  web:
    image: auxtel-web
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=0
      - 'RUN=flask run --host=0.0.0.0 --port=80
